### ISSUE TITLE
Am I Missing something?

### ISSUE THREAD

**Issue by Lokotito** [giannitedesco/project-mayhem#4]
I don't know what I'm doing wrong, installed in ubuntu 15.10.
Shows me the list of shows (names), but when I try to click in any then an error come in terminal:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/app/project-mayhem/pymayhem/webthread.py", line 35, in run
    self._do_work(work)
  File "/home/app/project-mayhem/pymayhem/webthread.py", line 72, in _do_work
    req.cb(r, d)
  File "/home/app/project-mayhem/pymayhem/webthread.py", line 125, in Closure
    cb(h.result, url)
  File "wmclient", line 387, in got_vars
    v = self.convert(d, url)
  File "wmclient", line 355, in convert
    v.sid = int(d['p_sid'])
KeyError: 'p_sid'

Am I missing something?

**Comment by giannitedesco** [comment]
That code is parsing the markup. Presumably the markup has changed since this code worked.
